#!/usr/bin/env python3

from lib.sylens_main import main

# Allows for script to be called sylens instead of sylens_main.py 
# Is the user runing this particular file
if __name__=='__main__':
    main()
